# Generated by Django 4.1.7 on 2023-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthority',
            name='is_Receptionist',
            field=models.BooleanField(default=False),
        ),
    ]
