# Generated by Django 4.1.7 on 2023-07-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0003_userauthority_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseriesload',
            name='Series_state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
